---
# Role check tasks

- name: check if sqlserver jdbc connector is installed
  stat:
    path: "{{ sqlserver_jdbc_connector_jar_path }}"
  register: sqlserver_jdbc_connector_jar_check_result
  # WTF!!
  # vars:
  #   distribution: "{{ ansible_facts.distribution | lower }}"
  tags:
    - role::sqlserver_jdbc_connector
    - role::sqlserver_jdbc_connector::check
